from fpdf import FPDF

def safe_text(text):
    """
    Remove all non-Latin-1 characters so FPDF won't crash.
    """
    if text is None:
        return ""
    return text.encode('latin-1', 'ignore').decode('latin-1')

def generate_feedback_pdf(match_score, skills_found, feedback_list, output_file="Tailored_CV_Report.pdf"):
    pdf = FPDF()
    pdf.add_page()
    pdf.set_auto_page_break(auto=True, margin=15)

    # Title
    pdf.set_font("Arial", 'B', 18)
    pdf.cell(0, 10, safe_text("xAI Resume Tailor Report"), ln=True, align="C")
    pdf.ln(10)

    # CV Match
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 8, safe_text(f"CV Match Score: {match_score}%"), ln=True)
    pdf.ln(5)

    # Skills detected
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 8, safe_text("Skills Detected in CV:"), ln=True)
    pdf.set_font("Arial", size=12)
    if skills_found:
        pdf.multi_cell(0, 8, safe_text(", ".join(skills_found)))
    else:
        pdf.multi_cell(0, 8, safe_text("No significant skills detected from predefined list."))
    pdf.ln(5)

    # Feedback / Suggestions
    pdf.set_font("Arial", 'B', 14)
    pdf.cell(0, 8, safe_text("Improvement Suggestions:"), ln=True)
    pdf.ln(3)
    pdf.set_font("Arial", size=12)
    for item in feedback_list:
        pdf.multi_cell(0, 8, safe_text(f"- {item}"))
        pdf.ln(2)

    # Footer
    pdf.ln(5)
    pdf.set_font("Arial", 'I', 10)
    pdf.multi_cell(0, 8, safe_text("Generated by Resumate — Premium AI CV Analysis"))

    pdf.output(output_file)
    return output_file
